# -*- coding: utf-8 -*-
"""Simple banking system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywxNTG1jj4U4_QsNkQZd93s2dFgVmsKk
"""

def create_account():
  acc_type=input("Enter type of account (current(1) or saving(2)): ")
  try:
    initial_balance=float(input("Enter initial balance: "))
    if initial_balance < 500:
      print("Initial balance cannot be less than 500.")
      return
    print(f"Account created successfully! Account type: {acc_type}, Initial balance: {initial_balance}")
  except ValueError:
    print("Invalid input. Please enter a valid number for the balance.")

def withdraw():
  try:
    acc_bal = float(input("Please enter the balance: "))
    print(f"Your account balance is {acc_bal}")
    withdraw = float(input("Please enter the amount to withdraw: "))
    if acc_bal < withdraw:
      print("Insufficient amount...")
    elif withdraw <500:
      print("Please enter a valid amount to withdraw.")
    else:
      print("Please collect your cash")
      new_bal = acc_bal - withdraw
      print(f"Your new balance is {new_bal}")
  except ValueError:
    print("Invalid input. Please enter a valid number.")
  except ZeroDivisionError:
    print("Division by zero error.")

def receipt():
  a=input("Want to print receipt(yes(1) or no(2)): ")
  try:
    if a=="1":
      print("receipt print successfully")
    else:
      print("receipt not print")
  except ValueError:
    print("Invalid input. Please enter a valid number.")
  except ZeroDivisionError:
    print("Division by zero error.")
    print("exit")

while True:
  print("Welcome to the Banking System")
  print("1.Create Account")
  print("2.Withdraw")
  print("3.receipt")
  print("4.Exit")
  choice=input("Enter your choice: ")

  if choice=="1":
    create_account()
  elif choice=="2":
    withdraw()
  elif choice=="3":
    receipt()
  elif choice=="4":
    print("Exiting...")
    break
  else:
    print("Invalid choice. Please try again.")

